apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "gpu-exporter.fullname" . }}
  labels:
    {{- include "gpu-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gpu-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gpu-exporter.selectorLabels" . | nindent 8 }}
    spec:
      hostPID: true
      serviceAccountName: {{ include "gpu-exporter.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: gpu-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --addr=:{{ .Values.service.port }}
            {{- range $key, $value := .Values.extraArgs }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            runAsUser: 0
