image:
  repository: caiocfer/gpu-exporter
  tag: v1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

service:
  port: 9835
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9835"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

nodeSelector: {}

tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule

nvidia:
  enabled: true
  libraryPaths:
    - /usr/lib/x86_64-linux-gnu
    - /usr/lib64

extraArgs: {}
