apiVersion: v1
entries:
  gpu-exporter:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-05-29T01:44:44.481500868-03:00"
    description: NVIDIA GPU metrics exporter with per-process resource correlation
    digest: 43c8888d1fc69d572fbffd27207e45a68ade7a85eb76b543456ad9c0213f0be7
    name: gpu-exporter
    type: application
    urls:
    - https://caiocfer.github.io/gpu-exporter/gpu-exporter-0.1.0.tgz
    version: 0.1.0
generated: "2026-05-29T01:44:44.481227095-03:00"
